### ISSUE TITLE
linux kernel 4.6.0 error 

### ISSUE THREAD

**Issue by moonman** [cryptodev-linux/cryptodev-linux#12]
Module won't compile with new kernel 4.6.0
```
DKMS make.log for cryptodev-1.8 for kernel 4.6.0-3-ARCH (armv7l)
Sat May 21 18:12:08 MDT 2016
/var/lib/dkms/cryptodev/1.8/build/zc.c: In function '__get_userbuf':
/var/lib/dkms/cryptodev/1.8/build/zc.c:62:23: warning: passing argument 1 of 'get_user_pages' makes integer from pointer without$
  ret = get_user_pages(task, mm,
                       ^~~~
In file included from /var/lib/dkms/cryptodev/1.8/build/zc.c:28:0:
include/linux/mm.h:1266:6: note: expected 'long unsigned int' but argument is of type 'struct task_struct *'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
/var/lib/dkms/cryptodev/1.8/build/zc.c:62:29: warning: passing argument 2 of 'get_user_pages' makes integer from pointer without$
  ret = get_user_pages(task, mm,
                             ^~
In file included from /var/lib/dkms/cryptodev/1.8/build/zc.c:28:0:
include/linux/mm.h:1266:6: note: expected 'long unsigned int' but argument is of type 'struct mm_struct *'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
/var/lib/dkms/cryptodev/1.8/build/zc.c:63:34: warning: passing argument 5 of 'get_user_pages' makes pointer from integer without$
    (unsigned long)addr, pgcount, write, 0, pg, NULL);
                                  ^~~~~
In file included from /var/lib/dkms/cryptodev/1.8/build/zc.c:28:0:
include/linux/mm.h:1266:6: note: expected 'struct page **' but argument is of type 'int'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
/var/lib/dkms/cryptodev/1.8/build/zc.c:62:8: error: too many arguments to function 'get_user_pages'
  ret = get_user_pages(task, mm,
        ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/cryptodev/1.8/build/zc.c:28:0:
include/linux/mm.h:1266:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
/var/lib/dkms/cryptodev/1.8/build/zc.c: In function 'release_user_pages':
/var/lib/dkms/cryptodev/1.8/build/zc.c:122:3: error: implicit declaration of function 'page_cache_release' [-Werror=implicit-fun$
   page_cache_release(ses->pages[i]);
   ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:291: recipe for target '/var/lib/dkms/cryptodev/1.8/build/zc.o' failed
make[2]: *** [/var/lib/dkms/cryptodev/1.8/build/zc.o] Error 1
Makefile:1428: recipe for target '_module_/var/lib/dkms/cryptodev/1.8/build' failed
make[1]: *** [_module_/var/lib/dkms/cryptodev/1.8/build] Error 2
Makefile:27: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by michaelweiser** [comment]
Please consider https://github.com/cryptodev-linux/cryptodev-linux/pull/14. I think it fixes the issue more thoroughly.

**Comment by moonman** [comment]
@michaelweiser your suggested patch is equivalent except it brakes cryptodev on kernels that have no put_page  (as suggested in the description on < 3.10 kernels )

**Comment by michaelweiser** [comment]
You misunderstood: I just stopped looking for when page_cache_release() was introduced and if it's always been an alias for put_page() because I thought 3.10 ancient enough. I've done some more checking: page_cache_release() has been an alias for put_page() since 2.6.0. Before that (at least as far back as 2.4.10) both page_cache_release() and put_page() have been an aliases for __free_page(), so will result in exactly the same code. Do we still support 2.2?

More importantly, I was actually referring to the use of get_user_pages_remote() because quite a lot of effort went into making parameters task and mm available at that point in the code. I guess there was a reason for that, namely accessing the memory of a task different from the current one after that task's decoupled/deferred asynchronous operation finished. If that's not the case, the whole handing-around of task and mm should be dropped as well, resulting in leaner function interfaces and data structures.

**Comment by moonman** [comment]
Makes sense. The lowest kernel we support is 3.8 so that was my main concern. I will close this PR so you can make one. Thank you.

**Comment by moonman** [comment]
Apologies, I thought this was the PR. Issue reopened, PR closed.

**Comment by moonman** [comment]
Fixed in https://github.com/cryptodev-linux/cryptodev-linux/commit/f14b4706b0d04988e7e5bc8c4d2aefef9f029d9d
