### ISSUE TITLE
The AES CTR cipher doesn't get any engine acceleration, due to an enum expected as a define

### ISSUE THREAD

**Issue by Retropotenza** [cryptodev-linux/cryptodev-linux#44]
Hello,

I've noticed that in https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/engine/eng_cryptodev.c the CRYPTO_AES_CTR is used for a preprocessor check.

In BSD https://github.com/openbsd/src/blob/master/sys/crypto/cryptodev.h is indeed declared with a #define.

In cryptdev-linux in instead declared in an enum, which makes it not defined for the preprocessor.

To make the AES CTR cipher engine acceleration works, I had to patch my OpenSSL. I would like to propose a patch here, but I don't see any other option rather than changing back that enum to a set of #define.

What do you think?

**Comment by cristian-stoica** [comment]
Such a patch looks extensive: I have no idea how clean it would be or what will break, if anything.

On the other hand OpenSSL moved to devcrypto where they added another check with !defined(CHECK_BSD_STYLE_MACROS). This looks like it should work as is. Doesn't it?

**Comment by cristian-stoica** [comment]
I have no idea what was going on at the time but this looks like an OpenSSL issue:
Original commit openssl/openssl@6ecbc2bb62835a401ad6efe240d469a23b21755b was cherry-picked and perpetuated ever since

**Comment by Retropotenza** [comment]
CHECK_BSD_STYLE_MACROS looks to be defined if CRYPTO_ALGORITHM_MIN is defined, but I'm not able to find anyplace where CRYPTO_ALGORITHM_MIN is :-(...

But yes, in the master branch of OpenSSL the engine should work as is.

Other versions of OpenSSL instead will be affected. The commit openssl/openssl@6ecbc2b was working correctly only with the BSD cryptodev.

**Comment by cristian-stoica** [comment]
By the looks of it, this is an issue with (now) older versions of OpenSSL. If necessary they can be patched more easily than we can adapt cryptodev to make it work with them.
I'm sorry but an extensive patch on our part doesn't seem such a good idea right now.

**Comment by Retropotenza** [comment]
I agree that this is an issue with older versions of OpenSSL. I think that I found a way to keep both defines and enums, even if the final resulting code looks ugly (see https://github.com/Retropotenza/cryptodev-linux/blob/master/crypto/cryptodev.h).

This header aims to keep compatibility with both the original BSD header, and the enum definition of cryptodev-linux. It should allows to use cryptodev-linux with any source code that was existing before (whether expecting defines or enums).

**Comment by cristian-stoica** [comment]
@Retropotenza I don't see a compelling reason for a fix in cryptodev.

Obviously the macro is defined in BSD so they have no problem and cryptodev-linux had support for AES-CTR when OpenSSL introduced the patch openssl/openssl@6ecbc2b . If they found it necessary to avoid offloading AES_CTR it was because of an non-obvious issue that I can only speculate on. Nikos was in charge so he could have made necessary fixes.

There is also the issue of API which was very loose: cryptodev-linux worked very well a long time without relying on macros instead of enums. OpenSSL even introduced in recent versions CHECK_BSD_STYLE_MACROS and that should make cryptodev-linux work as is.

This is an problem with OpenSSL1.0.2 and other older versions of OpenSSL.
If people find it necessary to incorporate such a change, OK. But I would like to hear more arguments before we proceed.

**Comment by Retropotenza** [comment]
Hello, I've created https://github.com/openssl/openssl/issues/8911 for this.
