### ISSUE TITLE
Openembedded out of tree patches

### ISSUE THREAD

**Issue by nmenon** [cryptodev-linux/cryptodev-linux#61]
Just wondering if we are interested in the 2 patches that I see OE carry for years now:
http://git.openembedded.org/openembedded-core/tree/meta/recipes-kernel/cryptodev/files

**Comment by cristian-stoica** [comment]
I don't remember exactly why the installation of the cryptodev.h header was disabled in that patch. I've seen the patches before but never used them myself.

I don't think it's a good idea to disable the header installation since it exposes the driver's interface as it is (not necessarily identical to the BSD cryptodev interface).

Who uses those patches and what for?

**Comment by denix0** [comment]
Don't worry about the second patch - it's marked as "Upstream-Status: Inappropriate [ OE specific ]".

It's only needed for split packaging - the .ko module goes into one binary package for the target, and .h header goes into another package for development.

On the other hand, the other patch to enable building and installing tests looks upstreamable - "Upstream-Status: Pending". Not sure if it was ever submitted though.

**Comment by nmenon** [comment]
Thanks @denix0 . yes, at least the make file [changes](http://git.openembedded.org/openembedded-core/tree/meta/recipes-kernel/cryptodev/files/0001-Add-the-compile-and-install-rules-for-cryptodev-test.patch)  did'nt seem to make it to upstream. @cristian-stoica would probably have a better view if it makes sense or not..

**Comment by cristian-stoica** [comment]
https://github.com/cryptodev-linux/cryptodev-linux/commit/7461d732c57052593592aa92f9aa964b92d3809e

**Comment by nmenon** [comment]
Thanks @cristian-stoica much appreciated.
