### ISSUE TITLE
What's the supported kernel version list?

### ISSUE THREAD

**Issue by abgnwl** [cryptodev-linux/cryptodev-linux#75]
Which kernel versions are supported by cryptodev-linux? 
Does it support all kernel versions with Kernel crypto API(since kernel version 2.5.45)?

**Comment by cristian-stoica** [comment]
It works on current Linux kernels and on the kernels that were contemporary with cryptodev at the time of each release.
Current cryptodev should work with some (all?) 4.x kernels since the code is selectively using the crypto API that was used in those kernels.

For really old kernels you probably have to run some tests.

From: Lizijue ***@***.***>
Sent: miercuri, 30 martie 2022 10:53
To: cryptodev-linux/cryptodev-linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [cryptodev-linux/cryptodev-linux] What's the supported kernel version list? (Issue #75)


Caution: EXT Email

Which kernel versions are supported by cryptodev-linux?
Does it support all kernel versions with Kernel crypto API(since kernel version 2.5.45)?

-

**Comment by abgnwl** [comment]
Thanks for your answer
